openapi: 3.0.1
info:
  title: API
  version: "1.0"
servers:
- url: /
paths:
  /gesamttubenAnz/Server1:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnz/Server2:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnz/Machine1/{serverID}:
    get:
      parameters:
      - explode: false
        in: path
        name: serverID
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnz/Machine2/{serverID}:
    get:
      parameters:
      - explode: false
        in: path
        name: serverID
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnz/Server1/Percent:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnz/Server2/Percent:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnz/TAA1/Percent:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnz/TAA2/Percent:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnz/TAA3/Percent:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnz/TAA4/Percent:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /resetBit/Machine1:
    post:
      responses:
        "200":
          description: Success
      tags:
      - API
  /resetBit/Machine2:
    post:
      responses:
        "200":
          description: Success
      tags:
      - API
  /gesamttubenanzZiel:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
    post:
      requestBody:
        content:
          application/json:
            schema:
              format: int32
              type: integer
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenanzZiel/MachinePairs:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenanzZiel/4Machines:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /timeInterval:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
    post:
      parameters:
      - explode: true
        in: query
        name: intervalValue
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
components:
  schemas: {}

