openapi: 3.0.1
info:
  title: API
  version: "1.0"
servers:
- url: /
paths:
  /gesamttubenAnzVisual/Server1:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnzVisual/Server2:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnzVisual/Server1/Percent:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnzVisual/Server2/Percent:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnzVisual/TAA1/Percent:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnzVisual/TAA2/Percent:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnzVisual/TAA3/Percent:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnzVisual/TAA4/Percent:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnzVisual/Machine1/{serverID}:
    get:
      parameters:
      - explode: false
        in: path
        name: serverID
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnzVisual/Machine2/{serverID}:
    get:
      parameters:
      - explode: false
        in: path
        name: serverID
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /report/information:
    get:
      parameters:
      - explode: true
        in: query
        name: dateTime
        required: true
        schema:
          format: date-time
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                additionalProperties:
                  items:
                    type: string
                  type: array
                type: object
          description: Success
      tags:
      - API
  /report/LastReportDate:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: Success
      tags:
      - API
  /report/LastGoalPercent:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnz/Machine1/{serverID}:
    get:
      parameters:
      - explode: false
        in: path
        name: serverID
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenAnz/Machine2/{serverID}:
    get:
      parameters:
      - explode: false
        in: path
        name: serverID
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /kaputteTubenAnz/TAA1:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
    put:
      parameters:
      - explode: true
        in: query
        name: value
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: boolean
          description: Success
      tags:
      - API
  /kaputteTubenAnz/TAA2:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
    put:
      parameters:
      - explode: true
        in: query
        name: value
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: boolean
          description: Success
      tags:
      - API
  /kaputteTubenAnz/TAA3:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
    put:
      parameters:
      - explode: true
        in: query
        name: value
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: boolean
          description: Success
      tags:
      - API
  /kaputteTubenAnz/TAA4:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
    put:
      parameters:
      - explode: true
        in: query
        name: value
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: boolean
          description: Success
      tags:
      - API
  /password/check:
    get:
      parameters:
      - explode: true
        in: query
        name: passwordValue
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: boolean
          description: Success
      tags:
      - API
  /password:
    get:
      responses:
        "200":
          content:
            text/plain:
              schema:
                type: string
          description: Success
      tags:
      - API
  /password/newPassword:
    put:
      parameters:
      - explode: true
        in: query
        name: newPasswordValue
        required: true
        schema:
          type: string
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: boolean
          description: Success
      tags:
      - API
  /resetBit/Server1:
    post:
      responses:
        "200":
          description: Success
      tags:
      - API
  /resetBit/Server2:
    post:
      responses:
        "200":
          description: Success
      tags:
      - API
  /gesamttubenanzZiel:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
    put:
      requestBody:
        content:
          application/json:
            schema:
              format: int32
              type: integer
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                type: boolean
          description: Success
      tags:
      - API
  /gesamttubenanzZiel/MachinePairs:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenanzZiel/4Machines:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /timeInterval:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
    put:
      parameters:
      - explode: true
        in: query
        name: intervalValue
        required: true
        schema:
          format: int32
          type: integer
        style: form
      responses:
        "200":
          content:
            application/json:
              schema:
                type: boolean
          description: Success
      tags:
      - API
components:
  schemas: {}

