openapi: 3.0.1
info:
  title: API
  version: "1.0"
servers:
- url: /
paths:
  /gesamttubenanz/Server1:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int64
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenanz/Server2:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int64
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenanz/Machine1/{serverID}:
    get:
      parameters:
      - explode: false
        in: path
        name: serverID
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int64
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenanz/Machine2/{serverID}:
    get:
      parameters:
      - explode: false
        in: path
        name: serverID
        required: true
        schema:
          format: int32
          type: integer
        style: simple
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int64
                type: integer
          description: Success
      tags:
      - API
  /gesamttubenanzZiel:
    get:
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
    post:
      requestBody:
        content:
          application/json:
            schema:
              format: int32
              type: integer
        required: true
      responses:
        "200":
          content:
            application/json:
              schema:
                format: int32
                type: integer
          description: Success
      tags:
      - API
  /resetBit/Server1:
    post:
      responses:
        "200":
          description: Success
      tags:
      - API
  /resetBit/Server2:
    post:
      responses:
        "200":
          description: Success
      tags:
      - API
components:
  schemas: {}

